language: rust
cache: cargo
sudo: required
rust:
- nightly
- beta
- 1.9.0
addons:
  postgresql: 9.4
before_script:
- "./.travis/setup.sh"
script:
- cargo test
- cargo test --features "with-uuid with-rustc-serialize with-time with-unix_socket with-serde_json with-chrono with-openssl with-bit-vec with-eui48"
- (test $TRAVIS_RUST_VERSION != "nightly" || cargo test --features nightly)
