language: rust
cache: cargo
sudo: required
rust:
- nightly
- beta
- 1.10.0
addons:
  postgresql: 9.4
before_script:
- "./.travis/setup.sh"
script:
- cargo test
- cargo test --features "with-uuid with-rustc-serialize with-time with-serde_json with-chrono with-openssl with-bit-vec with-eui48"
