[package]
name = "postgres"
version = "0.11.10"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://sfackler.github.io/rust-postgres/doc/v0.11.10/postgres"
readme = "README.md"
keywords = ["database", "postgres", "postgresql", "sql"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md", "THIRD_PARTY"]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[features]
nightly = []
with-bit-vec = ["bit-vec"]
with-chrono = ["chrono"]
with-eui48 = ["eui48"]
with-openssl = ["openssl", "openssl-verify"]
with-rustc-serialize = ["rustc-serialize"]
with-security-framework = ["security-framework"]
with-serde_json = ["serde_json"]
with-time = ["time"]
with-unix_socket = ["unix_socket"]
with-uuid = ["uuid"]

[dependencies]
bufstream = "0.1"
byteorder = "0.5"
hex = "0.2"
log = "0.3"
phf = "=0.7.15"
bit-vec = { version = "0.4", optional = true }
chrono = { version = "0.2.14", optional = true }
eui48 = { version = "0.1", optional = true }
openssl = { version = ">= 0.6.4, < 0.8", optional = true }
openssl-verify = { version = "0.1", optional = true }
rustc-serialize = { version = "0.3", optional = true }
security-framework = { version = "0.1.2", optional = true }
serde_json = { version = ">= 0.6, < 0.9", optional = true }
time = { version = "0.1.14", optional = true }
unix_socket = { version = "0.5", optional = true }
uuid = { version = ">= 0.1, < 0.3", optional = true }

[dev-dependencies]
url = "1.0"
